import turtle as t
s= t.Screen()
s.setup(height=500,width=500)
t.shape("turtle")
t.color("black")
t.pensize(3)
#ask for values
value_1=input("Enter the first value: ")
value_2=input("Enter the second value: ")
value_3=input("Enter the third value: ")
value_4=input("Enter the fourth value: ")
#draw y & x axis
t.speed("fastest")
t.penup()
t.setheading(180)
t.forward(200)
t.right(90)
t.forward(200)
t.pendown()
t.backward(400)
t.right(90)
t.forward(400)
t.penup()
t.backward(400)
t.speed("slow")
t.pensize(3)
#Draw bar 1
t.pendown()
t.left(90)
t.color("maroon","red")
t.begin_fill()
t.forward(int(value_1))
t.right(90)
t.forward(100)
t.right(90)
t.forward(int(value_1))
t.end_fill()
#Draw bar 2
t.left(180)
t.color("blue","cyan")
t.begin_fill()
t.forward(int(value_2))
t.right(90)
t.forward(100)
t.right(90)
t.forward(int(value_2))
t.end_fill()
#Draw bar 3
t.left(180)
t.color("black","green")
t.begin_fill()
t.forward(int(value_3))
t.right(90)
t.forward(100)
t.right(90)
t.forward(int(value_3))
t.end_fill()
#Draw bar 4
t.left(180)
t.color("purple","pink")
t.begin_fill()
t.forward(int(value_4))
t.right(90)
t.forward(100)
t.right(90)
t.forward(int(value_4))
t.end_fill()
print("Bar Graph Complete!")

t.done()
