import turtle as t
import random as r
s= t.Screen()
s.setup(height=500,width=500)
t.shape("arrow")
t.color("black")
t.pensize(3)
#draw the segments
t.speed("fastest")
t.forward(100)
t.right(90)
t.forward(200)
t.right(90)
t.forward(100)
t.right(90)
t.forward(200)
t.backward(100)
t.right(90)
t.forward(100)
#pick random number
num=r.randint(0,9)
print("Drawing",num)
#add if/else/elif statements
if num==0:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green")
  t.pendown()
  for i in range(2):
    t.forward(100)
    t.right(90)
    t.forward(200)
    t.right(90)
elif num==1:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green")
  t.forward(100)
  t.right(90)
  t.pendown()
  t.forward(200)
elif num==2:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green")
  t.pendown()
  t.forward(100)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.forward(100)
  t.left(90)
  t.forward(100)
  t.left(90)
  t.forward(100)
elif num==3:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green")
  t.pendown()
  t.forward(100)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.forward(100)
  t.backward(100)
  t.left(90)
  t.forward(100)
  t.right(90)
  t.forward(100)
elif num==4:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green")
  t.setheading(270)
  t.pendown()
  t.forward(100)
  t.left(90)
  t.forward(100)
  t.left(90)
  t.forward(100)
  t.backward(200)
elif num==5:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green") 
  t.pendown()
  t.forward(100)
  t.backward(100)
  t.right(90)
  t.forward(100)
  t.left(90)
  t.forward(100)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.forward(100)
elif num==6:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green") 
  t.pendown()
  t.forward(100)
  t.backward(100)
  t.right(90)
  t.forward(200)
  t.left(90)
  t.forward(100)
  t.left(90)
  t.forward(100)
  t.left(90)
  t.forward(100)
elif num==7:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green") 
  t.pendown()
  t.forward(100)
  t.right(90)
  t.forward(200)
elif num==8:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green") 
  t.pendown()
  t.forward(100)
  t.right(90)
  t.forward(200)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.forward(200)
  t.backward(100)
  t.right(90)
  t.forward(100)
else:
  t.penup()
  t.speed("slow")
  t.home()
  t.color("green") 
  t.pendown()
  t.forward(100)
  t.right(90)
  t.forward(200)
  t.backward(100)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.forward(100)
  
t.done()
